### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'bitem' not found in

### ISSUE THREAD

**Issue by ghost** [Frederick888/php-bencode#3]
i did install as per your instructions., added .so file in php.ini 

i can see in phpinfo();
```
Configuration

bencode

Version	1.2.3
Directive	Local Value	Master Value
bencode.namespace	1	1

```

i did reboot php-fpm , nginx

and tried test.php file 

```
<?php

$bnode = bitem::parse("d4:key1l5:hello5:worlde4:key2i99ee");
print_r($bnode->to_meta_array());
```

and got .,

```
[root@ns540545 ]# php test.php
PHP Fatal error:  Uncaught Error: Class 'bitem' not found in /usr/share/nginx/com/html/admin/updatepeers/test.php:3
Stack trace:
#0 {main}
  thrown in /usr/share/nginx/com/html/admin/updatepeers/test.php on line 3

```
what am i missing ?

sorry but i am not very much familiar with Object oriented coding.

i am trying parse 400 MB  bencoded file provided by tracker site.
Thanks

**Comment by ghost** [comment]
alright, after lots of trial and error., i came to know using namespace in oo.

here is working code.
```
<?php
namespace bencode;

$bnode = bitem::parse("d4:key1l5:hello5:worlde4:key2i99ee");
print_r($bnode->to_meta_array());
```

i ll try now big file , 400 MB and see performance.

thanks

**Comment by Frederick888** [comment]
You can actually change the setting to `bencode.namespace=0` so that the classes will not be registered in `bencode` namespace. Unless you need to avoid duplications of class names, there's no need to turn it on.

**Comment by ghost** [comment]
i did , enable it , so i guess., ill disable it.

Thanks for quick response.
