### ISSUE TITLE
Will not make

### ISSUE THREAD

**Issue by NibsNiven** [Frederick888/php-bencode#6]
tom@nova[~/src/php-bencode]$ make
/bin/sh /home/tom/src/php-bencode/libtool --mode=compile g++  -I. -I/home/tom/src/php-bencode -DPHP_ATOM_INC -I/home/tom/src/php-bencode/include -I/home/tom/src/php-bencode/main -I/home/tom/src/php-bencode -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -std=c++11 -g -O3   -c /home/tom/src/php-bencode/bencode.cc -o bencode.lo 
libtool: compile:  g++ -I. -I/home/tom/src/php-bencode -DPHP_ATOM_INC -I/home/tom/src/php-bencode/include -I/home/tom/src/php-bencode/main -I/home/tom/src/php-bencode -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -std=c++11 -g -O3 -c /home/tom/src/php-bencode/bencode.cc  -fPIC -DPIC -o .libs/bencode.o
In file included from /home/tom/src/php-bencode/bencode.cc:4:0:
/home/tom/src/php-bencode/bencode.cc: In function 'void zim_bitem_parse(zend_execute_data*, zval*)':
/home/tom/src/php-bencode/php_bencode.h:24:41: error: expected unqualified-id before '&' token
     } catch (const std::invalid_argument& ia) {                                                                 \
                                         ^
/home/tom/src/php-bencode/bencode.cc:22:5: note: in expansion of macro 'CALL_AND_HANDLE'
     CALL_AND_HANDLE(RETURN_ZVAL(bitem::parse(ben_str), 1, 1));
     ^
/home/tom/src/php-bencode/php_bencode.h:24:41: error: expected ')' before '&' token
     } catch (const std::invalid_argument& ia) {                                                                 \
                                         ^
/home/tom/src/php-bencode/bencode.cc:22:5: note: in expansion of macro 'CALL_AND_HANDLE'
     CALL_AND_HANDLE(RETURN_ZVAL(bitem::parse(ben_str), 1, 1));
     ^
/home/tom/src/php-bencode/php_bencode.h:24:41: error: expected '{' before '&' token
     } catch (const std::invalid_argument& ia) {                                                                 \
                                         ^
/home/tom/src/php-bencode/bencode.cc:22:5: note: in expansion of macro 'CALL_AND_HANDLE'
     CALL_AND_HANDLE(RETURN_ZVAL(bitem::parse(ben_str), 1, 1));
     ^
/home/tom/src/php-bencode/php_bencode.h:24:43: error: 'ia' was not declared in this scope
     } catch (const std::invalid_argument& ia) {                                                                 \
                                           ^
/home/tom/src/php-bencode/bencode.cc:22:5: note: in expansion of macro 'CALL_AND_HANDLE'
     CALL_AND_HANDLE(RETURN_ZVAL(bitem::parse(ben_str), 1, 1));
     ^
/home/tom/src/php-bencode/php_bencode.h:24:45: error: expected ';' before ')' token
     } catch (const std::invalid_argument& ia) {                                                                 \
                                             ^
/home/tom/src/php-bencode/bencode.cc:22:5: note: in expansion of macro 'CALL_AND_HANDLE'
     CALL_AND_HANDLE(RETURN_ZVAL(bitem::parse(ben_str), 1, 1));
     ^
/home/tom/src/php-bencode/bencode.cc:745:1: error: expected '}' at end of input
 }
 ^
make: *** [bencode.lo] Error 1

**Comment by Frederick888** [comment]
Just dropping your build log here doesn't make it a *proper* bug report. And actually I just ran the CI again and it compiled without any hiccups against PHP 7.1, 7.2 and 7.3.

Please come back with more info.

**Comment by Frederick888** [comment]
Stale. Open a new one with details if needed.
