### ISSUE TITLE
Raspberry Pi4 segfault

### ISSUE THREAD

**Issue by DJATOM** [Frederick888/php-bencode#9]
For some reason I'm getting segfault when trying to call `to_array()` method. 
Using gdb I have found that crash occurs at [this place](https://github.com/Frederick888/php-bencode/blob/98b5dfbe121ccd150d212518c294a5fa21d6fc04/src/zend_container.h#L95).
Maybe it's something ARM-related, but anyway bug is a bug, so reporting it.
```
(gdb) r -a
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/php -a
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Interactive mode enabled

php > $f = bencode\bitem::load("*****/1471.torrent");
php > var_dump($f->get_path("info")->get_path("files")->to_array());

Program received signal SIGSEGV, Segmentation fault.
0xb481e2b0 in blist::to_array (this=0x8a5948, include_meta=<optimized out>) at /home/pi/php-bencode/src/zend_container.h:95
95              return (bitem *)(*((uintptr_t *)((char *)obj - sizeof(uintptr_t))));
(gdb)
```

**Comment by Frederick888** [comment]
(lol this is a 'cringe over my old crappy code' moment)

IIRC 32bit Pi OS is still the preferred distribution? Are you using 32bit or 64bit? And PHP version by the way?

And could you test if https://github.com/Frederick888/php-bencode/commit/8e036b861f2a63c785102c9c47ec7def1f012afd fixes your issue?

**Comment by DJATOM** [comment]
Now it's just
```
php > $f = bencode\bitem::load("***/1471.torrent");
php > var_dump($f->get_path("info")->get_path("files")->to_array());

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
```
> IIRC 32bit Pi OS is still the preferred distribution? 

I downloaded a lite version of Raspbian when it arrived, apparently it was 32 bit. 
Pi4 board can work with 64 bit distro, but it seems like not a common practice for Pi devices.
I'm tinkering with php7.4, and php-bencode works on my Intel-based server (64 bit). So I assume it's not a php issue.

**Comment by Frederick888** [comment]
@DJATOM I'm afraid personally I'm not very keen on 32bit system compatibility, especially considering I haven't got any good 32bit development setup at hand.

A little searching led me to https://www.raspberrypi.org/forums/viewtopic.php?t=275370 though. Apparently there's a 64bit beta Pi OS (full & lite) now, which you can give a shot.

PR is still welcome of course.

**Comment by DJATOM** [comment]
Okay, Will try 64 bit later. I have to backup current data first.

**Comment by DJATOM** [comment]
So I tested and aarch64 works. So it's a 32 bit pointer issue?
Maybe you can add a notice about support for 32 bit OS, so people like me will not "step on a rake" again.

**Comment by Frederick888** [comment]
I found an old Pi Zero and I believe I got this fixed: https://github.com/Frederick888/php-bencode/commit/6ad2a632d81d5ebac96818749aba09fcac8aaecc

It's actually an alignment issue. `sizeof(uintptr_t)` is 4 here as expected but somehow offset of `bitem_object#std` is 8.

**Comment by DJATOM** [comment]
Well, I have entire 32 bit OS backup, but will not restore it just to check it out 😄 
Yeah, my friend also said that it could be an alignment issue.

**Comment by Frederick888** [comment]
Understandable lol.

I'll merge it for now but will hold off on releasing a new version. Hope there'll be someone to confirm this down the line.
